SELECT PLAYER_NAME ,PLAYER_ID, TEAM_NAME , LEAGUE_NAME , TOTAL_SQUADS_MADE AS Tsm , TOTAL_MATCH_INVOLVEMENTS AS Tgp ,  TOTAL_MINUTESPLAYED AS TMP , TOTAL_GOALS AS TG , TOTAL_ASSISTS AS TA
FROM AGG_PLAYER

WHERE TEAM_NAME = 'Liverpool'
ORDER BY LEAGUE_NAME , TEAM_NAME , TG desc , TA desc