--  Set Up Specfic User and Roles , which will be used via DBT for the main Transformation Processes


-- Step 1: Create Warehouse
CREATE OR REPLACE WAREHOUSE FOOTBALL_DEV_DBT_WH
WITH WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;

-- Step 2: Create Role and Assign It to Admins
CREATE OR REPLACE ROLE DBT_DEV_ROLE;
GRANT ROLE DBT_DEV_ROLE TO ROLE SYSADMIN;
GRANT ROLE DBT_DEV_ROLE TO ROLE USERADMIN;

-- Step 3: Grant Warehouse Access
GRANT USAGE, MONITOR ON WAREHOUSE FOOTBALL_DEV_DBT_WH TO ROLE DBT_DEV_ROLE;

-- Step 4: Create User and Assign Role
CREATE OR REPLACE USER DBT_DEV_USER
PASSWORD = 'FOOTBALL123data'
DEFAULT_ROLE = DBT_DEV_ROLE
DEFAULT_WAREHOUSE = FOOTBALL_DEV_DBT_WH
DEFAULT_NAMESPACE = DEV_FOOTBALL.DEV_FOOTBALL
MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE DBT_DEV_ROLE TO USER DBT_DEV_USER;

-- Step 5: Grant Database-Level Access to DEV_FOOTBALL
GRANT USAGE, MONITOR ON DATABASE DEV_FOOTBALL TO ROLE DBT_DEV_ROLE;

-- Step 6: Grant Ownership
GRANT OWNERSHIP ON SCHEMA DEV_FOOTBALL.DEV_FOOTBALL TO ROLE DBT_DEV_ROLE;


-- Step 8: Grant Read-Only Access to RAW_FOOTBALL (BBC_DEV)
GRANT USAGE ON DATABASE RAW_FOOTBALL TO ROLE DBT_DEV_ROLE;
GRANT USAGE ON SCHEMA RAW_FOOTBALL.BBC_DEV TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW_FOOTBALL.BBC_DEV TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_FOOTBALL.BBC_DEV TO ROLE DBT_DEV_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW_FOOTBALL.BBC_DEV TO ROLE DBT_DEV_ROLE;

-- Step 9: Confirm User and Role Permissions
SHOW GRANTS TO USER DBT_DEV_USER;
SHOW GRANTS TO ROLE DBT_DEV_ROLE;
SHOW GRANTS ON WAREHOUSE FOOTBALL_DEV_DBT_WH;



SHOW GRANTS ON SCHEMA DEV_FOOTBALL.DEV_FOOTBALL;


SHOW GRANTS ON VIEW DEV_FOOTBALL.DEV_FOOTBALL.STG_MATCH_RESULTS;







