-- Revoke and Remove user and Roles


REVOKE ROLE DBT_DEV_ROLE FROM USER DBT_DEV_USER;

REVOKE ROLE DBT_DEV_ROLE FROM ROLE SYSADMIN;

REVOKE ROLE DBT_DEV_ROLE FROM ROLE USERADMIN;

DROP USER IF EXISTS DBT_DEV_USER;

DROP ROLE IF EXISTS DBT_DEV_ROLE;

SHOW USERS;
SHOW ROLES;
SHOW WAREHOUSES;

SHOW GRANTS ON DATABASE RAW_FOOTBALL